In [21]:
α = [-1, 1]
θ = [1, 1]
# γ = [0, 0]
# β = [0, -0]
γ = [1, 1]
β = [1, -0.5]

include("model.ji")

main (generic function with 2 methods)

In [23]:
n = 200
p = length(α)
@time main(γ, θ, α, β, n)

  4.460206 seconds (31.09 M allocations: 3.267 GiB, 29.20% gc time)


([0.8805340856509261, -0.3513621010881447], [0.5688491108546775 1.488121528748243])

In [44]:
Theta = zeros(100, p)
Alpha = zeros(100, p)
import Base.Threads.@threads

In [45]:
t = time()
@threads for i in 1:5
        for j in 1:20
    Alpha[20*(i - 1) + j, :], Theta[20*(i - 1) + j, :] = main(γ, θ, α, β, n)
    end
end
println("MC Computing time: ", time() - t)
println(sum(Alpha, dims = 1))
println(sum(Theta, dims = 1))

MC Computing time: 390.9887399673462
[0.687943568402615 -7.9592538266731765]
[46.29942926840183 93.46973510846844]


In [46]:
ct, dc, mc = qgplsim.collection(sign.(Alpha))

(Any[[-1.0, 1.0], [1.0, 1.0], [1.0, -1.0], [-1.0, -1.0]], Dict{Any,Any}([1.0, 1.0] => [2, 3, 5, 32, 35, 37, 38, 45, 57, 79, 93, 99],[-1.0, -1.0] => [7, 8, 10, 21, 25, 31, 47, 50, 53, 60, 62, 65, 70, 71, 74, 77, 85, 91, 95, 100],[-1.0, 1.0] => [1, 6, 12, 18, 20, 23, 29, 30, 36, 44  …  76, 80, 81, 84, 86, 87, 88, 92, 94, 98],[1.0, -1.0] => [4, 9, 11, 13, 14, 15, 16, 17, 19, 22  …  68, 72, 73, 78, 82, 83, 89, 90, 96, 97]), [1.0, -1.0])

In [47]:
mc

2-element Array{Float64,1}:
  1.0
 -1.0

In [48]:
rAlpha = Alpha[dc[mc], :]
rTheta = Theta[dc[mc], :]

37×2 Array{Float64,2}:
 0.592443  1.47331
 0.615264  1.52076
 0.790859  1.30904
 0.976917  0.846437
 0.939544  1.01859
 0.901163  0.923416
 0.934293  0.961157
 0.932782  0.702972
 0.770918  1.35022
 0.558119  1.50611
 0.929708  1.06897
 0.98745   0.705064
 0.595297  1.49611
 ⋮         
 0.992793  0.897857
 0.921297  0.65393
 0.82858   1.10904
 0.912367  1.00778
 0.712054  1.41335
 0.993132  1.00756
 0.906642  0.989804
 0.682379  1.40761
 0.960423  0.845744
 0.857391  0.748432
 0.860143  1.05436
 0.927323  0.687913

In [49]:
sum(rAlpha, dims = 1)/37

1×2 Array{Float64,2}:
 0.652736  -0.63019

In [50]:
sum(rTheta, dims = 1)/37

1×2 Array{Float64,2}:
 0.849753  1.07851