In [87]:
α = [-1, 2]
θ = [2, 1]
# γ = [0, 0]
# β = [0, -0]
γ = [1, 1]
β = [1, -0.5]

include("model.ji")

main (generic function with 2 methods)

In [94]:
n = 400
p = length(α)
@time main(γ, θ, α, β, n)

  3.672292 seconds (64.02 M allocations: 6.778 GiB, 23.91% gc time)


([0.39371593344895534, -0.8466088548420829], [1.9112949724982025 0.9844706418553797])

In [95]:
Theta = zeros(100, p)
Alpha = zeros(100, p)
import Base.Threads.@threads

In [96]:
t = time()
len = 50
@threads for i in 1:2
        for j in 1:len
    Alpha[len*(i - 1) + j, :], Theta[len*(i - 1) + j, :] = main(γ, θ, α, β, n)
    end
end
println("MC Computing time: ", time() - t)
println(sum(Alpha, dims = 1))
println(sum(Theta, dims = 1))

MC Computing time: 323.4554908275604
[-2.700128727061028 -1.6154989372956057]
[172.30625706533854 127.94480447227332]


In [97]:
ct, dc, mc = qgplsim.collection(sign.(Alpha))

(Any[[1.0, -1.0], [-1.0, 1.0], [1.0, 1.0], [-1.0, -1.0]], Dict{Any, Any}([-1.0, -1.0] => [15, 17, 32, 55, 61, 67, 71], [1.0, -1.0] => [1, 7, 8, 9, 11, 12, 13, 16, 20, 25  …  80, 86, 88, 89, 90, 91, 93, 94, 98, 100], [-1.0, 1.0] => [2, 3, 5, 6, 10, 14, 18, 19, 21, 22  …  82, 83, 84, 85, 87, 92, 95, 96, 97, 99], [1.0, 1.0] => [4, 23]), [-1.0, 1.0])

In [98]:
mc

2-element Vector{Float64}:
 -1.0
  1.0

In [99]:
rAlpha = Alpha[dc[mc], :]
rTheta = Theta[dc[mc], :]
ns, = size(rAlpha)

(46, 2)

In [100]:
sum(rAlpha, dims = 1)/ns

1×2 Matrix{Float64}:
 -0.513305  0.77423

In [101]:
sum(rTheta, dims = 1)/ns

1×2 Matrix{Float64}:
 1.88714  1.34862

In [102]:
rAlpha

46×2 Matrix{Float64}:
 -0.377318  0.839499
 -0.46092   0.846883
 -0.468893  0.814145
 -0.485088  0.743328
 -0.328247  0.896704
 -0.640363  0.626013
 -0.473226  0.810604
 -0.466657  0.841857
 -0.657547  0.640302
 -0.544418  0.751497
 -0.653704  0.666701
 -0.50047   0.844559
 -0.533772  0.679421
  ⋮         
 -0.600642  0.74625
 -0.410455  0.895524
 -0.521948  0.775801
 -0.556154  0.734452
 -0.550869  0.79537
 -0.686815  0.638778
 -0.592428  0.679409
 -0.532023  0.79154
 -0.538158  0.751023
 -0.237888  0.958567
 -0.700856  0.631538
 -0.700164  0.55606

search: merge merge! mergewith mergewith! MergeSort



```
merge(d::AbstractDict, others::AbstractDict...)
```

Construct a merged collection from the given collections. If necessary, the types of the resulting collection will be promoted to accommodate the types of the merged collections. If the same key is present in another collection, the value for that key will be the value it has in the last collection listed. See also [`mergewith`](@ref) for custom handling of values with the same key.

# Examples

```jldoctest
julia> a = Dict("foo" => 0.0, "bar" => 42.0)
Dict{String, Float64} with 2 entries:
  "bar" => 42.0
  "foo" => 0.0

julia> b = Dict("baz" => 17, "bar" => 4711)
Dict{String, Int64} with 2 entries:
  "bar" => 4711
  "baz" => 17

julia> merge(a, b)
Dict{String, Float64} with 3 entries:
  "bar" => 4711.0
  "baz" => 17.0
  "foo" => 0.0

julia> merge(b, a)
Dict{String, Float64} with 3 entries:
  "bar" => 42.0
  "baz" => 17.0
  "foo" => 0.0
```

---

```
merge(a::NamedTuple, bs::NamedTuple...)
```

Construct a new named tuple by merging two or more existing ones, in a left-associative manner. Merging proceeds left-to-right, between pairs of named tuples, and so the order of fields present in both the leftmost and rightmost named tuples take the same position as they are found in the leftmost named tuple. However, values are taken from matching fields in the rightmost named tuple that contains that field. Fields present in only the rightmost named tuple of a pair are appended at the end. A fallback is implemented for when only a single named tuple is supplied, with signature `merge(a::NamedTuple)`.

!!! compat "Julia 1.1"
    Merging 3 or more `NamedTuple` requires at least Julia 1.1.


# Examples

```jldoctest
julia> merge((a=1, b=2, c=3), (b=4, d=5))
(a = 1, b = 4, c = 3, d = 5)
```

```jldoctest
julia> merge((a=1, b=2), (b=3, c=(d=1,)), (c=(d=2,),))
(a = 1, b = 3, c = (d = 2,))
```

---

```
merge(a::NamedTuple, iterable)
```

Interpret an iterable of key-value pairs as a named tuple, and perform a merge.

```jldoctest
julia> merge((a=1, b=2, c=3), [:b=>4, :d=>5])
(a = 1, b = 4, c = 3, d = 5)
```

---

```
 merge(counters...)
```

Creates a new counter with total counts equal to the sum of the counts in the counters given as arguments.

See also merge!

---

```
merge(sc1, sc2...)
```

This returns a SortedDict or SortedMultiDict that results from merging SortedDicts or SortedMultiDicts `sc1`, `sc2`, etc., which all must have the same key-value-ordering types. In the case of keys duplicated among the arguments, the rightmost argument that owns the key gets its value stored for SortedDict. In the case of SortedMultiDict all the key-value pairs are stored, and for keys shared between `sc1` and `sc2` the ordering is left-to-right. This function is not available for SortedSet, but the `union` function (see below) provides equivalent functionality. Time: O(*cN* log *N*), where *N* is the total size of all the arguments.

---

```
merge(sc1, sc2...)
```

This returns a SortedDict or SortedMultiDict that results from merging SortedDicts or SortedMultiDicts `sc1`, `sc2`, etc., which all must have the same key-value-ordering types. In the case of keys duplicated among the arguments, the rightmost argument that owns the key gets its value stored for SortedDict. In the case of SortedMultiDict all the key-value pairs are stored, and for keys shared between `sc1` and `sc2` the ordering is left-to-right. This function is not available for SortedSet, but the `union` function (see below) provides equivalent functionality. Time: O(*cN* log *N*), where *N* is the total size of all the arguments.

---

```
merge(h::Histogram, others::Histogram...)
```

Construct a new histogram by merging `h` with `others`. All histograms must have the same binning, shape of weights and properties (`closed` and `isdensity`). The weights of all histograms are summed up for each bin, the weights of the resulting histogram will have the same type as those of `h`.
