In [1]:
using DataFrames, CSV

In [2]:
using Statistics

In [6]:
filename = "./datasets/student-mat.csv"
df0 = DataFrame(CSV.File(filename))
df0[1:5,:]

5×33 DataFrame. Omitted printing of 26 columns
│ Row │ school  │ sex     │ age   │ address │ famsize │ Pstatus │ Medu  │
│     │ String3 │ String1 │ Int64 │ String1 │ String3 │ String1 │ Int64 │
├─────┼─────────┼─────────┼───────┼─────────┼─────────┼─────────┼───────┤
│ 1   │ GP      │ F       │ 18    │ U       │ GT3     │ A       │ 4     │
│ 2   │ GP      │ F       │ 17    │ U       │ GT3     │ T       │ 1     │
│ 3   │ GP      │ F       │ 15    │ U       │ LE3     │ T       │ 1     │
│ 4   │ GP      │ F       │ 15    │ U       │ GT3     │ T       │ 4     │
│ 5   │ GP      │ F       │ 16    │ U       │ GT3     │ T       │ 3     │

In [7]:
names(df0)

33-element Vector{String}:
 "school"
 "sex"
 "age"
 "address"
 "famsize"
 "Pstatus"
 "Medu"
 "Fedu"
 "Mjob"
 "Fjob"
 "reason"
 "guardian"
 "traveltime"
 ⋮
 "internet"
 "romantic"
 "famrel"
 "freetime"
 "goout"
 "Dalc"
 "Walc"
 "health"
 "absences"
 "G1"
 "G2"
 "G3"

In [10]:
grades = df0[[:G1, :G2, :G3]]
head(grades)

6×3 DataFrame
│ Row │ G1    │ G2    │ G3    │
│     │ Int64 │ Int64 │ Int64 │
├─────┼───────┼───────┼───────┤
│ 1   │ 5     │ 6     │ 6     │
│ 2   │ 5     │ 5     │ 6     │
│ 3   │ 7     │ 8     │ 10    │
│ 4   │ 15    │ 14    │ 15    │
│ 5   │ 6     │ 10    │ 10    │
│ 6   │ 15    │ 15    │ 15    │

#  Boston Datasets

In [4]:
filename = "./datasets/Boston.csv"
df = DataFrame(CSV.File(filename))
df[1:5,:]

5×15 DataFrame. Omitted printing of 8 columns
│ Row │ Column1 │ crim    │ zn      │ indus   │ chas  │ nox     │ rm      │
│     │ Int64   │ Float64 │ Float64 │ Float64 │ Int64 │ Float64 │ Float64 │
├─────┼─────────┼─────────┼─────────┼─────────┼───────┼─────────┼─────────┤
│ 1   │ 1       │ 0.00632 │ 18.0    │ 2.31    │ 0     │ 0.538   │ 6.575   │
│ 2   │ 2       │ 0.02731 │ 0.0     │ 7.07    │ 0     │ 0.469   │ 6.421   │
│ 3   │ 3       │ 0.02729 │ 0.0     │ 7.07    │ 0     │ 0.469   │ 7.185   │
│ 4   │ 4       │ 0.03237 │ 0.0     │ 2.18    │ 0     │ 0.458   │ 6.998   │
│ 5   │ 5       │ 0.06905 │ 0.0     │ 2.18    │ 0     │ 0.458   │ 7.147   │

In [5]:
names(df)

15-element Vector{String}:
 "Column1"
 "crim"
 "zn"
 "indus"
 "chas"
 "nox"
 "rm"
 "age"
 "dis"
 "rad"
 "tax"
 "ptratio"
 "black"
 "lstat"
 "medv"

In [143]:
name_of_y = :medv
names_of_x = [:rm, :ptratio, :lstat]
names_of_z = [:rad, :chas]

2-element Vector{Symbol}:
 :rad
 :chas

In [144]:
dfy = df[!, name_of_y]
dfX = df[!, names_of_x]
dfZ = df[!, names_of_z]

506×2 DataFrame
 Row │ rad    chas  
     │ Int64  Int64 
─────┼──────────────
   1 │     1      0
   2 │     2      0
   3 │     2      0
   4 │     3      0
   5 │     3      0
   6 │     3      0
   7 │     5      0
   8 │     5      0
   9 │     5      0
  10 │     5      0
  11 │     5      0
  ⋮  │   ⋮      ⋮
 497 │     6      0
 498 │     6      0
 499 │     6      0
 500 │     6      0
 501 │     6      0
 502 │     1      0
 503 │     1      0
 504 │     1      0
 505 │     1      0
 506 │     1      0
    485 rows omitted

In [145]:
dft = DataFrame(randn(500,2), :auto)

500×2 DataFrame
 Row │ x1           x2        
     │ Float64      Float64   
─────┼────────────────────────
   1 │  0.263919     0.814072
   2 │ -1.03512      1.25373
   3 │ -0.815591    -0.345523
   4 │ -0.594139    -0.936824
   5 │  0.191646    -0.975697
   6 │ -0.0964613    0.868968
   7 │  0.255583     1.23312
   8 │  0.0807954   -1.16969
   9 │  0.46921     -0.315457
  10 │ -0.82015     -1.14332
  11 │  0.0488062    0.920558
  ⋮  │      ⋮           ⋮
 491 │  0.494521     1.80023
 492 │  0.270532    -2.58242
 493 │ -1.07061     -2.1688
 494 │  0.648219    -0.522982
 495 │ -0.00567463   0.822157
 496 │  0.739406    -0.755996
 497 │ -0.750874    -1.76903
 498 │ -0.774356     0.256214
 499 │ -0.77213     -0.144401
 500 │ -0.787498     1.24391
              479 rows omitted

# GlM fitting

In [57]:
using GLM

In [65]:
formula = Term(name_of_y) ~ sum([Term(x) for x in names_of_x])

FormulaTerm
Response:
  medv(unknown)
Predictors:
  rm(unknown)
  ptratio(unknown)
  lstat(unknown)

In [66]:
model = lm(formula, df)

StatsModels.TableRegressionModel{LinearModel{GLM.LmResp{Vector{Float64}}, GLM.DensePredChol{Float64, LinearAlgebra.CholeskyPivoted{Float64, Matrix{Float64}}}}, Matrix{Float64}}

medv ~ 1 + rm + ptratio + lstat

Coefficients:
──────────────────────────────────────────────────────────────────────────
                 Coef.  Std. Error       t  Pr(>|t|)  Lower 95%  Upper 95%
──────────────────────────────────────────────────────────────────────────
(Intercept)  18.5671     3.9132       4.74    <1e-05  10.8788    26.2554
rm            4.51542    0.425872    10.60    <1e-23   3.67871    5.35213
ptratio      -0.930723   0.117654    -7.91    <1e-13  -1.16188   -0.699568
lstat        -0.571806   0.0422302  -13.54    <1e-35  -0.654775  -0.488836
──────────────────────────────────────────────────────────────────────────

In [69]:
using QuantReg

┌ Info: Precompiling QuantReg [a0becc08-653f-40d2-91e7-721373d1053f]
└ @ Base loading.jl:1342
┌ Warning: Module DataFrames with build ID 738569760042 is missing from the cache.
│ This may mean DataFrames [a93c6f00-e57d-5684-b7b6-d8193f3e46c0] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:1030
┌ Info: Skipping precompilation since __precompile__(false). Importing QuantReg [a0becc08-653f-40d2-91e7-721373d1053f].
└ @ Base loading.jl:1047
┌ Info: Precompiling JuMP [4076af6c-e467-56ae-b986-b466b2749572]
└ @ Base loading.jl:1342
┌ Warning: Module JSON with build ID 734442267042 is missing from the cache.
│ This may mean JSON [682c06a0-de6a-54ab-a142-c8b1cf79cde6] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:1030
┌ Warning: Module JSON with build ID 734442267042 is missing from the cache.
│ This may mean JSON [682c06a0-de6a-54ab-a142-c8b1cf79cde6] does not support precompilation but is imported by a mod

In [70]:
qmodel = QuantRegModel(formula, df)


medv ~ 1 + rm + ptratio + lstat, τ=0.5
Unfitted.

In [71]:
QuantReg.fit(qmodel)

────────────────────────
             Coefficient
────────────────────────
(Intercept)     9.36174
rm              5.28597
ptratio        -0.791082
lstat          -0.48072
────────────────────────


medv ~ 1 + rm + ptratio + lstat, τ=0.5


Degrees of freedom: 506 total; 502 residual


In [156]:
names_of_x2 = [:rm, :ptratio, :lstat, :chas]
formula2 = Term(name_of_y) ~ sum([Term(x) for x in names_of_x2])

FormulaTerm
Response:
  medv(unknown)
Predictors:
  rm(unknown)
  ptratio(unknown)
  lstat(unknown)
  chas(unknown)

In [158]:
lm(formula2, df)

StatsModels.TableRegressionModel{LinearModel{GLM.LmResp{Vector{Float64}}, GLM.DensePredChol{Float64, LinearAlgebra.CholeskyPivoted{Float64, Matrix{Float64}}}}, Matrix{Float64}}

medv ~ 1 + rm + ptratio + lstat + chas

Coefficients:
──────────────────────────────────────────────────────────────────────────
                 Coef.  Std. Error       t  Pr(>|t|)  Lower 95%  Upper 95%
──────────────────────────────────────────────────────────────────────────
(Intercept)  18.1364     3.8645       4.69    <1e-05  10.5438    25.729
rm            4.42644    0.42105     10.51    <1e-22   3.5992     5.25368
ptratio      -0.887437   0.116706    -7.60    <1e-12  -1.11673   -0.658144
lstat        -0.575495   0.0416979  -13.80    <1e-36  -0.657419  -0.493571
chas          3.43707    0.912613     3.77    0.0002   1.64405    5.23009
──────────────────────────────────────────────────────────────────────────

# QGPLSIM fitting

In [121]:
include("qgplsim.ji")

Main.qgplsim

In [148]:
X = Array(dfX)
y = Array(dfy)
Z = Array(dfZ.chas)
# Z = [ones(506) Z]
# Z = zeros(506)
X = (X - repeat(minimum(X, dims = 1), 506, 1))./ (repeat(maximum(X, dims = 1), 506, 1) - repeat(minimum(X, dims = 1), 506, 1))
X = X .* 2 .- 1
minimum(X, dims = 1)

1×3 Matrix{Float64}:
 -1.0  -1.0  -1.0

In [149]:
qsmodel = qgplsim.model(X, Z, y)
alpha, gamma, theta, beta = qgplsim.estimator(qsmodel)

([0.804267328442983, 0.0, 0.594267670666331], [-0.047742361209723264], [-3.5690552216926243 0.0 4.830272030443192], [8.779087665411428])

In [82]:
groupby(dfZ, :chas)

GroupedDataFrame with 2 groups based on key: chas
First Group (471 rows): chas = 0
 Row │ rad    chas  
     │ Int64  Int64 
─────┼──────────────
   1 │     1      0
   2 │     2      0
   3 │     2      0
   4 │     3      0
   5 │     3      0
   6 │     3      0
   7 │     5      0
   8 │     5      0
   9 │     5      0
  10 │     5      0
  11 │     5      0
  ⋮  │   ⋮      ⋮
 461 │     6      0
 462 │     6      0
 463 │     6      0
 464 │     6      0
 465 │     6      0
 466 │     6      0
 467 │     1      0
 468 │     1      0
 469 │     1      0
 470 │     1      0
 471 │     1      0
    449 rows omitted
⋮
Last Group (35 rows): chas = 1
 Row │ rad    chas  
     │ Int64  Int64 
─────┼──────────────
   1 │     5      1
   2 │     5      1
   3 │     5      1
   4 │     5      1
   5 │     5      1
   6 │     5      1
   7 │     5      1
   8 │     4      1
   9 │     4      1
  10 │     4      1
  11 │     4      1
  ⋮  │   ⋮      ⋮
  25 │     4      1
  26 │     5      1
  27 │     1      1
  28 │    24      1
  29 │    24      1
  30 │    24      1
  31 │    24      1
  32 │    24      1
  33 │    24      1
  34 │    24      1
  35 │    24      1
     13 rows omitted

In [126]:
n, = size(Z)

(506, 2)

In [115]:
typeof(Z) <: Vector

true